Interactive list
Enoisong/TodoList pull request #3
Opened 2023-04-07 23:27 UTC by Enoisong

### At this point in this project, I:
- Add some functionality to make my application  interactive
- Add a new JavaScript file and import it as a module:
- Add event listener to the checkbox (change).
- Update items object's value for completed key upon user actions.
- Implement a function for the "Clear all completed" button.
- Store the updated array of items in local storage.

2023-04-07 23:54 UTC, BenMukebo requested changes
### Hi @Enoisong,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻q
- No linter errors. ✔️ 
- GitHuvflow was correctly used.  ✔️   
- The task object's values for `completed` is updated upon user actions. ✔️   
- A function for the "Clear all completed" button is implemented. ✔️   
- The updated array of items is stored in local storage. ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 23:54 UTC, BenMukebo commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] Actually, you have two README files, the one from the root folder and the other in the src folder. Kindly remove one. 🚮

2023-04-07 23:54 UTC, BenMukebo commented on src/index.js
> +const clearBtn = document.querySelector('.clear-btn');
- [ ] According to Project requirements you should create a new JavaScript file to contain methods related to the status updates (completed: true / false).and import it as a module:
- Kindly make this. 👎🏻

2023-04-08 02:19 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @Enoisong,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

- [OPTIONAL] Kindly remove the Author on lines 98 and 99 in the Readme 

<img width="831" alt="Screenshot 2023-04-07 at 19 08 08" src="https://user-images.githubusercontent.com/81444338/230698967-da66cb2b-1f9e-48c1-a86a-c2681ab3315a.png">


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-04-08 02:36 UTC, merged